# Generated by Django 5.0.1 on 2024-01-08 14:22

from django.conf import settings
from django.db import migrations


def create_superuser(apps, editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Token = apps.get_model("authtoken", "Token")

    initial_user = User.objects.create_superuser(username="johndoe", email='johndoe@gmail.com', password='test123')
    Token.objects.get_or_create(user=initial_user, key="b58b602c1912e9432cbd0be58b9761040775bc3a")



class Migration(migrations.Migration):

    dependencies = [
        ('sleepapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser, migrations.RunPython.noop),
    ]
